export default [
    {
        code: 'W',
        name: 'WELCOME',
        grade: 'WELCOME',

        condition: '가입 시 자동',
        columnClass: 'c-welcome',
        accrualText: '1% 적립',
        coupons: [
            {
                id: 'w-1',
                className: 'c-hotel',
                label: '숙소쿠폰',
                type: 'amount', // 금액 쿠폰
                amount: 10000,
                condition: '5만 원 이상 결제 시',
                period: '연중',
                disabled: false,
            },
            {
                id: 'w-2',
                className: 'c-hotel',
                label: '숙소쿠폰',
                type: 'amount',
                amount: 5000,
                condition: '일부 한정 상품 적용',
                period: '연중',
                disabled: false,
            },
        ],
    },
    {
        code: 'F',
        name: 'FAMILY',
        grade: 'FAMILY',
        condition: '6개월 동안 10만원 이상',
        columnClass: 'c-family',
        accrualText: '2% 적립',
        coupons: [
            {
                id: 'f-1',
                className: 'c-hotel',
                label: '숙소쿠폰',
                type: 'amount',
                amount: 10000,
                condition: '10만 원 이상 결제 시',
                period: '연 2회',
                disabled: false,
            },
            {
                id: 'f-2',
                className: 'c-tour',
                label: '투어쿠폰',
                type: 'amount',
                amount: 5000,
                condition: '5만 원 이상 결제 시',
                period: '연 1회',
                disabled: false,
            },
        ],
    },
    {
        code: 'V',
        name: 'VIP',
        grade: 'VIP',
        condition: '6개월 동안 30만원 이상',
        columnClass: 'c-vip',
        accrualText: '3% 적립',
        coupons: [
            {
                id: 'v-1',
                className: 'c-hotel',
                label: '숙소쿠폰',
                type: 'percent', // 퍼센트 쿠폰
                amount: 10,
                condition: '10만 원 이상 결제 시',
                period: '연 1회',
                disabled: false,
            },
            {
                id: 'v-2',
                className: 'c-tour',
                label: '투어쿠폰',
                type: 'amount',
                amount: 10000,
                condition: '10만 원 이상 결제 시',
                period: '연 1회',
                disabled: false,
            },
        ],
    },
    {
        code: 'V',
        name: 'VVIP',
        grade: 'VVIP',
        condition: '6개월 동안 50만원 이상',
        columnClass: 'c-vvip',
        accrualText: '4% 적립',
        coupons: [
            {
                id: 'vv-1',
                className: 'c-hotel',
                label: '숙소쿠폰',
                type: 'amount',
                amount: 30000,
                condition: '이용권 제공',
                period: '연 1회',
                disabled: false,
            },
            {
                id: 'vv-2',
                className: 'c-tour',
                label: '투어쿠폰',
                type: 'percent',
                amount: 10,
                condition: '이용권 제공',
                period: '연 1회',
                disabled: false,
            },
        ],
    },
];
