// src/api/packagesData.js
export default [
    // 1. 드라마 - 갯마을 차차차
    {
        contents: '드라마',
        title: '갯마을 차차차',
        subtitle: '포항 구룡포·청진항 패키지',
        subtitle2: '포항 구룡포·청진항',
        desc: '잔잔한 바닷마을 풍경 속, 드라마 속 힐링 장소를 직접 걸어보는 여행',
        backgroundImg: '/images/tour/main/guryongpo-bg.png',
        posterImg: '/images/tour/main/chachacha.png',
        thumbImg: '/images/tour/main/chachacha_thumb.png',
        benefits: [
            { icon: 'walk', text: '바닷마을 산책' },
            { icon: 'cafe', text: '핫플 카페 2곳' },
            { icon: 'map', text: '로케 지도 제공' },
            { icon: 'bus', text: '왕복 셔틀' },
        ],
        images: [
            '/images/tour/detail/hometown-chachacha-1.jpg',
            '/images/tour/detail/hometown-chachacha-2.jpg',
        ],
        slug: 'hometown-chachacha-tour',
        date: '상시출발',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: 'KTX 왕복',
        shopping: '자유쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 390000,
        child_fee: 350000,
        // ✅ 오늘 기준으로 매일 출발
        schedule: { freq: 'DAILY' },
        itinerary: [
            {
                day: 1,
                country: '대한민국',
                city: '포항',
                tours: [
                    { place: '서울역 → KTX 포항역', desc: '고속열차로 편리한 이동' },
                    { place: '청진항', desc: '드라마 공진 마을 중심 배경' },
                    {
                        place: '홍반장과 윤혜진 첫 만남 장소',
                        desc: '항구 풍경 & 바닷가 포토스팟',
                    },
                    { place: '구룡포 바닷가', desc: '드라마 다수 촬영, 바닷가 산책' },
                    {
                        place: '포항 죽도시장',
                        desc: '저녁 – 회, 물회, 과메기 등 지역 특산물',
                    },
                ],
                hotel: {
                    name: '오션뷰 호텔',
                    room_type: '2인 1실',
                    desc: '바다 전망 숙소',
                },
            },
            {
                day: 2,
                country: '대한민국',
                city: '포항',
                tours: [
                    { place: '구룡포 일본인가옥거리', desc: '드라마 촬영지 & 포토존' },
                    { place: '구룡포항 빨간등대', desc: '홍반장 주요 촬영지' },
                    { place: '구룡포 해산물 요리', desc: '점심 – 로컬 해산물' },
                    {
                        place: '호미곶 해맞이 광장',
                        desc: '상생의 손 조형물, 인증샷 필수',
                    },
                    { place: '포항운하 크루즈', desc: '도심 속 바다 감상' },
                    { place: '포항 시내 레스토랑', desc: '저녁 – 해산물 파인다이닝' },
                ],
                hotel: {
                    name: '온천 & 스파 호텔',
                    room_type: '2인 1실',
                    desc: '휴식 및 스파 체험',
                },
            },
            {
                day: 3,
                country: '대한민국',
                city: '포항',
                tours: [
                    { place: '영일대 해수욕장 & 스카이워크', desc: '바다 위 유리전망대' },
                    { place: '포항 바다 전망 카페', desc: '루프탑 카페 투어' },
                    { place: '점심', desc: '지역 맛집' },
                    { place: '포항역 → 서울역', desc: 'KTX 복귀' },
                ],
                hotel: { name: '', room_type: '', desc: '숙박 없음' },
            },
        ],
        flight_info: {
            departure: {
                airline: 'KTX',
                time_start: '09:00',
                time_end: '12:00',
                airport_start: '서울역',
                airport_end: '포항역',
                duration: '3시간',
            },
            arrival: {
                time_start: '15:00',
                time_end: '18:00',
                airport_start: '포항역',
                airport_end: '서울역',
                duration: '3시간',
            },
        },
    },

    // 2. 예능 - 윤식당
    {
        contents: '예능',
        title: '윤식당 2',
        subtitle: '스페인 테네리페 패키지',
        subtitle2: '스페인 테네리페',
        desc: '태양의 섬에서 예능 속 따뜻한 분위기를 그대로 경험하는 휴양 여행',
        backgroundImg: '/images/tour/main/tenerife-bg.png',
        posterImg: '/images/tour/main/younskitchen2.png',
        thumbImg: '/images/tour/main/younskitchen2_thumb.png',
        benefits: [
            { icon: 'calendar', text: '6박 8일' },
            { icon: 'airplane', text: '왕복 항공권' },
            { icon: 'hotel', text: '4성급 호텔' },
            { icon: 'food', text: '조식 포함' },
        ],
        images: [
            '/images/tour/detail/youns-kitchen-1.jpg',
            '/images/tour/detail/youns-kitchen-2.jpg',
        ],
        slug: 'younskitchen2-tenerife',
        date: '상시출발',
        duration: '3박 4일',
        nights: 3,
        days: 4,
        flight: '대한항공 직항',
        shopping: '현지 자유시간 포함',
        guide_fee: '포함',
        optional: true,
        adult_fee: 1390000,
        child_fee: 1200000,
        // 필요 시 departures: ['2025-11-05','2025-11-12'] 같이 고정일을 넣어도 됩니다.
        itinerary: [
            {
                day: 1,
                country: '스페인',
                city: '테네리페',
                tours: [
                    { place: '테네리페 도착', desc: '공항 이동 및 호텔 체크인' },
                    { place: '가라치코 마을 산책', desc: '윤식당 촬영지 첫 만남' },
                ],
                hotel: {
                    name: '가라치코 시내 호텔',
                    room_type: '2인 1실',
                    desc: '스페인 전통 감성 호텔',
                },
            },
        ],
        flight_info: {
            departure: {
                airline: '대한항공',
                flight_number: 'KE123',
                time_start: '10:00',
                time_end: '18:00',
                airport_start: '인천공항',
                airport_end: '마드리드공항',
                duration: '14시간',
            },
            arrival: {
                time_start: '11:00',
                time_end: '06:00',
                airport_start: '마드리드공항',
                airport_end: '인천공항',
                duration: '13시간',
            },
        },
    },

    // 3. 드라마 - 폭싹 속았수다
    {
        contents: '드라마',
        title: '폭싹 속았수다',
        subtitle: '고창 청보리밭 패키지',
        subtitle2: '고창 청보리밭',
        desc: '푸른 청보리밭 사이로 드라마 속 명장면을 재현하는 힐링 로드',
        backgroundImg: '/images/tour/main/jeju-bg.png',
        posterImg: '/images/tour/main/tangerines.png',
        thumbImg: '/images/tour/main/tangerines_thumb.png',
        benefits: [
            { icon: 'calendar', text: '2박 3일' },
            { icon: 'hotel', text: '부티크호텔' },
            { icon: 'food', text: '조식 2회' },
            { icon: 'ticket', text: '입장권 포함' },
        ],
        images: [
            '/images/tour/detail/when-life-gives-you-tangerines-01.jpg',
            '/images/tour/detail/when-life-gives-you-tangerines-2.jpg',
        ],
        slug: 'when-life-gives-you-tangerines',
        date: '상시출발',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: '김포-제주 왕복',
        shopping: '자유쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 420000,
        child_fee: 380000,
        // ✅ 오늘 기준으로 매일 출발
        schedule: { freq: 'DAILY' },
        itinerary: [
            {
                day: 1,
                country: '대한민국',
                city: '제주',
                tours: [
                    { place: '김포공항 → 제주공항', desc: '제주 도착' },
                    { place: '이호테우 해변', desc: '말등대 인증샷' },
                    { place: '용두암 & 탑동 광장', desc: '드라마 산책로' },
                    { place: '제주시 흑돼지 거리', desc: '저녁 – 흑돼지 BBQ' },
                ],
                hotel: {
                    name: '제주시내 호텔',
                    room_type: '2인 1실',
                    desc: '첫째 날 숙박',
                },
            },
            {
                day: 2,
                country: '대한민국',
                city: '제주',
                tours: [
                    { place: '성산일출봉', desc: '드라마 명장면 배경' },
                    { place: '섭지코지 & 드라마 하우스', desc: '실제 세트 촬영지' },
                    { place: '표선해수욕장', desc: '바닷마을 장면' },
                    { place: '카멜리아 힐', desc: '감성 꽃길' },
                    { place: '서귀포 매일 올레시장', desc: '저녁 – 로컬 먹거리' },
                ],
                hotel: {
                    name: '서귀포 오션뷰 호텔',
                    room_type: '2인 1실',
                    desc: '바다 전망 숙소',
                },
            },
            {
                day: 3,
                country: '대한민국',
                city: '제주',
                tours: [
                    { place: '한담 해안 산책로', desc: '드라마 명장면' },
                    { place: '오설록 티뮤지엄', desc: '녹차밭 감성' },
                    { place: '점심', desc: '갈치조림/성게미역국' },
                    { place: '제주공항 귀환', desc: '서울 복귀' },
                ],
                hotel: { name: '', room_type: '', desc: '숙박 없음' },
            },
        ],
        flight_info: {
            departure: {
                airline: '대한항공',
                time_start: '09:00',
                time_end: '10:10',
                airport_start: '김포공항',
                airport_end: '제주공항',
                duration: '1시간 10분',
            },
            arrival: {
                time_start: '15:00',
                time_end: '16:10',
                airport_start: '제주공항',
                airport_end: '김포공항',
                duration: '1시간 10분',
            },
        },
    },

    // 4. 영화 - 범죄도시4
    {
        contents: '영화',
        title: '범죄도시 4',
        subtitle: '필리핀 보홀 섬 패키지',
        subtitle2: '필리핀 보홀 섬',
        desc: '액션 영화 촬영 현장의 열기를 느낄 수 있는 남국의 섬 여행',
        backgroundImg: '/images/tour/main/bohol-bg.png',
        posterImg: '/images/tour/main/crimecity4.png',
        thumbImg: '/images/tour/main/crimecity4_thumb.png',
        benefits: [
            { icon: 'calendar', text: '3박 5일' },
            { icon: 'airplane', text: '대한항공' },
            { icon: 'shopping', text: '쇼핑 3회' },
            { icon: 'dollar', text: '가이드 $60' },
            { icon: 'flag', text: '선택 관광' },
        ],
        images: [
            '/images/tour/detail/the-round-up-1.webp',
            '/images/tour/detail/the-round-up-2.png',
        ],
        slug: 'crimecity4-bohol-tour',
        date: '상시출발',
        duration: '3박 5일',
        nights: 3,
        days: 5,
        flight: '대한항공',
        shopping: '쇼핑 3회 포함',
        guide_fee: '$60',
        optional: true,
        adult_fee: 1590000,
        child_fee: 1390000,
        // ✅ 범죄도시4 패키지 데이터 추가
        itinerary: [
            {
                day: 1,
                country: '필리핀',
                city: '보홀',
                tours: [
                    { place: '인천국제공항', desc: '필리핀 항공편 탑승' },
                    { place: '보홀 팡라오 국제공항 도착', desc: '가이드 미팅 후 리조트로 이동' },
                    { place: '리조트 체크인 후 자유시간', desc: '영화 속 주인공처럼 휴식 시작' },
                ],
                hotel: {
                    name: '헤난 리조트',
                    room_type: '2인 1실',
                    desc: '보홀 최대 규모의 리조트에서 편안한 휴식',
                },
            },
            {
                day: 2,
                country: '필리핀',
                city: '보홀',
                tours: [
                    { place: '초콜릿 힐', desc: '영화 속 추격전 배경, 독특한 지형의 언덕 탐험' },
                    { place: '로복강 투어', desc: '선상 위에서 즐기는 전통 뷔페식 점심' },
                    { place: '타르시어 원숭이 보호 구역', desc: '세계에서 가장 작은 원숭이 관찰' },
                    { place: '비나리안 악어 농장', desc: '스릴 넘치는 액션 주인공의 흔적 찾기' },
                ],
                hotel: {
                    name: '헤난 리조트',
                    room_type: '2인 1실',
                    desc: '아름다운 보홀의 밤을 즐기는 편안한 숙소',
                },
            },
            {
                day: 3,
                country: '필리핀',
                city: '보홀',
                tours: [
                    { place: '발리카삭 호핑투어', desc: '투명한 바다에서 거북이와 함께 수영' },
                    {
                        place: '스노클링 & 스쿠버 다이빙',
                        desc: '아름다운 산호초와 열대어 관찰 (선택관광)',
                    },
                    { place: '버진 아일랜드', desc: '신비로운 모래섬에서의 휴식' },
                    { place: '마사지 체험', desc: '여행의 피로를 풀어주는 힐링 시간' },
                ],
                hotel: {
                    name: '헤난 리조트',
                    room_type: '2인 1실',
                    desc: '리조트 수영장에서 마지막 밤을 만끽하세요',
                },
            },
            {
                day: 4,
                country: '필리핀',
                city: '보홀',
                tours: [
                    { place: '리조트 자유시간', desc: '여유롭게 즐기는 오전' },
                    { place: '시내 쇼핑', desc: '기념품과 현지 특산품 구매 (쇼핑 3회 포함)' },
                    { place: '보홀 팡라오 국제공항', desc: '공항으로 이동' },
                ],
                hotel: {
                    name: '',
                    room_type: '',
                    desc: '숙박 없음',
                },
            },
            {
                day: 5,
                country: '대한민국',
                city: '인천',
                tours: [{ place: '인천국제공항 도착', desc: '한국 도착 후 해산' }],
                hotel: {
                    name: '',
                    room_type: '',
                    desc: '숙박 없음',
                },
            },
        ],
        flight_info: {
            departure: {
                airline: '대한항공',
                flight_number: 'KE651',
                time_start: '21:00',
                time_end: '00:30',
                airport_start: '인천국제공항',
                airport_end: '보홀 팡라오 국제공항',
                duration: '4시간 30분',
            },
            arrival: {
                airline: '대한항공',
                flight_number: 'KE652',
                time_start: '01:30',
                time_end: '07:00',
                airport_start: '보홀 팡라오 국제공항',
                airport_end: '인천국제공항',
                duration: '4시간 30분',
            },
        },
    },

    // 5. K-POP - BTS
    {
        contents: 'K-POP',
        title: 'BTS',
        subtitle: '콘서트/뮤직비디오 패키지',
        subtitle2: '콘서트/뮤직비디오',
        desc: 'BTS가 다녀간 뮤비/공연 장소를 따라가는 팬 성지순례 투어',
        backgroundImg: '/images/tour/main/bts-bg.png',
        posterImg: '/images/tour/main/bts-yet-to-come.png',
        thumbImg: '/images/tour/main/bts_thumb.png',
        benefits: [
            { icon: 'calendar', text: '2박 3일' },
            { icon: 'ticket', text: '영화 관람 포함' },
            { icon: 'hotel', text: '특급호텔' },
            { icon: 'tourbus', text: 'BTS 성지 투어' },
        ],
        images: ['/images/tour/detail/bts-1.jpg', '/images/tour/detail/bts-2.jpg'],
        slug: 'bts-yet-to-come-tour',
        date: '일정 고정 (1~6명)',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: 'KTX/항공',
        shopping: '자유 쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 650000,
        child_fee: 600000,
        itinerary: [
            {
                day: 1,
                country: '대한민국',
                city: '서울',
                tours: [
                    { place: '하이브 인사이트', desc: 'BTS·세븐틴 전시관' },
                    { place: 'SM타운 플래그십 스토어', desc: '굿즈 & 세계관 체험' },
                    { place: '한강 유람선', desc: '네온 조명·음악 퍼포먼스' },
                ],
                hotel: {
                    name: '서울 시내 호텔',
                    room_type: '2인 1실',
                    desc: 'K-POP 팬 감성 숙소',
                },
            },
            {
                day: 2,
                country: '대한민국',
                city: '서울',
                tours: [
                    { place: '경복궁 & 북촌 한옥마을', desc: '전통과 판타지 조화' },
                    { place: '점심: 전통 한식', desc: '한정식·퓨전 한식' },
                    { place: 'K-팝 댄스 클래스', desc: '아이돌 안무 배우기' },
                    { place: '홍대 라이브 클럽', desc: '판타지적 무대 체험' },
                ],
                hotel: {
                    name: '서울 호텔',
                    room_type: '2인 1실',
                    desc: '홍대·강남 접근성',
                },
            },
            {
                day: 3,
                country: '대한민국',
                city: '서울',
                tours: [
                    { place: '동대문 DDP', desc: '미래적 건축물' },
                    { place: '명동 K-푸드 투어', desc: '치킨·떡볶이·호떡' },
                    { place: '뮤직비디오 거리', desc: '촬영지 산책 후 귀환' },
                ],
                hotel: { name: '', room_type: '', desc: '숙박 없음' },
            },
        ],
        flight_info: {
            departure: {
                airline: '개별 이동',
                airport_start: '집결지',
                airport_end: '서울',
            },
            arrival: { airport_start: '서울', airport_end: '귀가' },
        },
    },

    // 6. K-POP - BLACKPINK
    {
        contents: 'K-POP',
        title: 'BLACKPINK',
        subtitle: '콘서트/뮤직비디오 패키지',
        subtitle2: '콘서트/뮤직비디오',
        desc: '글로벌 스타 블랙핑크의 무대와 뮤비 촬영지를 직접 방문하는 특별한 투어',
        backgroundImg: '/images/tour/main/blackpink-3.png',
        posterImg: '/images/tour/main/blackpink.png',
        thumbImg: '/images/tour/main/blackpink_thumb.png',
        benefits: [
            { icon: 'calendar', text: '2박 3일' },
            { icon: 'hotel', text: '5성급 호텔' },
            { icon: 'ticket', text: '콘서트 티켓 포함' },
            { icon: 'shopping', text: '굿즈샵 투어' },
        ],
        images: ['/images/tour/detail/blackpink-1.jpg', '/images/tour/detail/blackpink-2.jpg'],
        slug: 'blackpink-worldtour-seoul',
        date: '일정 고정 (1~6명)',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: '서울 집결',
        shopping: '굿즈샵 포함',
        guide_fee: '포함',
        optional: false,
        adult_fee: 580000,
        child_fee: 540000,
        itinerary: [
            {
                day: 1,
                country: '대한민국',
                city: '서울',
                tours: [
                    { place: 'YG 엔터 본사 외관', desc: '블링크 필수 코스' },
                    { place: '하이브 인사이트', desc: 'K-POP 전시관 체험' },
                    { place: '저녁: 홍대 K-팝 레스토랑', desc: '테마 레스토랑' },
                ],
                hotel: {
                    name: '홍대 인근 호텔',
                    room_type: '2인 1실',
                    desc: '블랙핑크 감성 숙소',
                },
            },
            {
                day: 2,
                country: '대한민국',
                city: '서울',
                tours: [
                    { place: '한강공원', desc: '연습생 시절 감성 재현' },
                    { place: '홍대 댄스 클래스', desc: '블핑 안무 배우기' },
                    { place: 'DDP', desc: '패션·뮤직비디오 촬영지' },
                    { place: '이태원 루프탑 바', desc: '글로벌 팬 감성' },
                ],
                hotel: {
                    name: '강남권 호텔',
                    room_type: '2인 1실',
                    desc: '쇼핑 최적화 숙소',
                },
            },
            {
                day: 3,
                country: '대한민국',
                city: '서울',
                tours: [
                    { place: '명동 K-팝 굿즈샵', desc: '앨범·포토카드 쇼핑' },
                    { place: '남산타워 전망 레스토랑', desc: '점심 – 서울 전경 감상' },
                    { place: '귀환', desc: '서울역/공항' },
                ],
                hotel: { name: '', room_type: '', desc: '숙박 없음' },
            },
        ],
        flight_info: {
            departure: {
                airline: '개별 이동',
                airport_start: '집결지',
                airport_end: '서울',
            },
            arrival: { airport_start: '서울', airport_end: '귀가' },
        },
    },

    // 7. 예능 - 서진이네
    {
        contents: '예능',
        title: '서진이네 2',
        subtitle: '멕시코 바칼라르 패키지',
        subtitle2: '멕시코 바칼라르',
        desc: '청량한 호수 위 수상 하우스에서 즐기는 느긋한 힐링 투어',
        backgroundImg: '/images/tour/main/bacalar-bg.png',
        posterImg: '/images/tour/main/seojin.png',
        thumbImg: '/images/tour/main/seojin_thumb.png',
        benefits: [
            { icon: 'calendar', text: '4박 6일' },
            { icon: 'boat', text: '라군 보트 투어' },
            { icon: 'food', text: '로컬 맛집 3회' },
            { icon: 'camera', text: '촬영 포인트 방문' },
        ],
        images: ['/images/tour/detail/seojin-1.jpg', '/images/tour/detail/seojin-2.webp'],
        slug: 'seojin-mexico-bacalar',
        date: '출발일 지정',
        duration: '3박 4일',
        nights: 3,
        days: 4,
        flight: '대한항공 + 멕시코 국내선',
        shopping: '현지 마켓 투어 포함',
        guide_fee: '포함',
        optional: true,
        adult_fee: 1990000,
        child_fee: 1790000,
        itinerary: [
            {
                day: 1,
                country: '스페인',
                city: '테네리페',
                tours: [
                    { place: '테네리페 도착', desc: '공항 이동 및 호텔 체크인' },
                    { place: '가라치코 마을 산책', desc: '윤식당 촬영지 첫 만남' },
                ],
                hotel: {
                    name: '가라치코 시내 호텔',
                    room_type: '2인 1실',
                    desc: '스페인 전통 감성 호텔',
                },
            },
        ],
        flight_info: {
            departure: {
                airline: '대한항공',
                flight_number: 'KE123',
                time_start: '10:00',
                time_end: '18:00',
                airport_start: '인천공항',
                airport_end: '마드리드공항',
                duration: '14시간',
            },
            arrival: {
                time_start: '11:00',
                time_end: '06:00',
                airport_start: '마드리드공항',
                airport_end: '인천공항',
                duration: '13시간',
            },
        },
    },

    // 8. 영화 - 하얼빈
    {
        contents: '영화',
        title: '하얼빈',
        subtitle: '몽골 고비사막 패키지',
        subtitle2: '몽골 고비사막',
        desc: '광활한 고비사막에서 영화 속 장면처럼 낙타 트래킹을 즐기는 이색 투어',
        backgroundImg: '/images/tour/main/harbin-bg.png',
        posterImg: '/images/tour/main/harbin.png',
        thumbImg: '/images/tour/main/harbin_thumb.png',
        benefits: [
            { icon: 'calendar', text: '3박 4일' },
            { icon: 'hotel', text: '특급호텔' },
            { icon: 'plane', text: '항공 포함' },
            { icon: 'gift', text: '기념품 증정' },
        ],
        images: ['/images/tour/detail/harbin-1.jpg', '/images/tour/detail/harbin-2.webp'],
        slug: 'harbin-film-tour',
        date: '매주 월요일 출발',
        duration: '3박 4일',
        nights: 3,
        days: 4,
        flight: '대한항공 직항',
        shopping: '자유 쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 1290000,
        child_fee: 1090000,
        schedule: { freq: 'WEEKLY', byWeekday: ['MO'] },
        itinerary: [
            {
                day: 1,
                title: '인천 출발, 몽골 입국',
                theme: '출발',
                description:
                    '인천 공항에서 출발하여 몽골 울란바토르 칭기즈 칸 국제공항에 도착합니다. 현지 가이드와 미팅 후 호텔로 이동하여 여장을 풀고, 몽골 전통 환영식과 만찬을 즐깁니다.',
                meals: {
                    breakfast: '불포함',
                    lunch: '기내식',
                    dinner: '포함',
                },
                accommodation: '울란바토르 시내 특급호텔',
                highlight: '몽골 전통 만찬',
                activities: ['공항 미팅', '호텔 체크인', '환영 만찬'],
                transport: '전용 차량',
                image: 'harbin-day1.jpg',
            },
            {
                day: 2,
                title: '고비사막 투어 시작',
                theme: '고비사막',
                description:
                    '국내선 항공편을 이용하여 고비사막의 관문인 달란자드가드로 이동합니다. 도착 후 고비사막의 웅장함을 느끼며 영화 속 하얼빈 장면처럼 사막 트래킹을 경험합니다. 석양 아래에서 즐기는 낙타 트래킹은 잊지 못할 추억을 선사할 것입니다.',
                meals: {
                    breakfast: '포함',
                    lunch: '현지식',
                    dinner: '포함',
                },
                accommodation: '사막 게르 캠프',
                highlight: '낙타 트래킹, 사막 석양',
                activities: ['국내선 이동', '사막 트래킹', '낙타 체험', '별 관측'],
                transport: '국내선 항공, 전용 차량',
                image: 'harbin-day2.jpg',
            },
            {
                day: 3,
                title: '고비사막의 대자연 탐험',
                theme: '자연',
                description:
                    '고비사막의 대표 명소인 홍고린 엘스와 욜링 암을 방문합니다. 거대한 모래 언덕인 홍고린 엘스에서 모래썰매를 타거나, 얼음 계곡인 욜링 암에서 신비로운 자연의 경관을 감상합니다. 밤에는 끝없이 펼쳐진 몽골의 밤하늘 아래에서 별 관측 투어를 진행합니다.',
                meals: {
                    breakfast: '포함',
                    lunch: '현지식',
                    dinner: '포함',
                },
                accommodation: '사막 게르 캠프',
                highlight: '홍고린 엘스(모래 언덕), 욜링 암(얼음 계곡)',
                activities: ['모래 언덕 체험', '욜링 암 탐험', '별 관측 투어'],
                transport: '전용 차량',
                image: 'harbin-day3.jpg',
            },
        ],

        flight_info: [
            {
                leg: 1,
                from: '인천 (ICN)',
                to: '울란바토르 (ULN)',
                flight_num: 'KE867',
                airline: '대한항공',
                departure_time: '13:00',
                arrival_time: '16:00',
                duration: '3시간 30분',
                note: '현지 시간 기준',
            },
            {
                leg: 2,
                from: '울란바토르 (ULN)',
                to: '인천 (ICN)',
                flight_num: 'KE868',
                airline: '대한항공',
                departure_time: '17:00',
                arrival_time: '21:00',
                duration: '3시간',
                note: '현지 시간 기준',
            },
        ],
    },
];
